name: setup-r-test
on:
  push:
    branches:
      - main

jobs:
  test-setup-r:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
         r-version: '3.5.3' # The R version to download (if necessary) and use.
      - run: Rscript -e 'print("hello")'
  
